//! Security tests: the parsers against hostile input, read off disk.
//!
//! Test Plan §12 (SEC-001..SEC-007). Every fixture in `tests/fixtures/malformed/`
//! is consumed here.
//!
//! The contract under test is narrow and absolute: **no input, however crafted,
//! may panic, hang, or allocate without bound.** A malformed file must produce a
//! typed `EngineError`. These parsers are the engine's only attack surface —
//! they are the one component that touches bytes the user did not author.

use osu_engine::error::EngineError;
use osu_engine::parser::{osr::parse_osr, osu::parse_osu};

use std::path::PathBuf;

fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/malformed")
        .join(rel)
}

fn read(rel: &str) -> Vec<u8> {
    std::fs::read(fixture(rel)).unwrap_or_else(|e| panic!("missing fixture {rel}: {e}"))
}

/// SEC-001: an LZMA bomb must be rejected on the output cap.
///
/// The fixture is a real bomb: 44 KB of payload that expands to 300 MB, past the
/// 256 MB cap. It is generated by actually compressing 300 MB of zeroes, not by
/// forging a size header, so it exercises the streaming path rather than an
/// early sanity check.
///
/// The assertion that matters is not merely "returns an error" — it is that the
/// error is the *cap*, proving decompression was aborted mid-stream rather than
/// completing and then being measured.
#[test]
fn sec_001_lzma_bomb_is_rejected_on_the_cap() {
    let bomb = read("lzma_bomb.osr");

    assert!(
        bomb.len() < 100 * 1024,
        "fixture should be small; it is {} bytes",
        bomb.len()
    );

    match parse_osr(&bomb, Some(14)) {
        Err(EngineError::DecompressionOutputTooLarge { limit_bytes, .. }) => {
            assert_eq!(limit_bytes, 256 * 1024 * 1024);
        }
        other => panic!("expected DecompressionOutputTooLarge, got {other:?}"),
    }
}

/// SEC-002: a ULEB128 length declaring 2^32 bytes must be rejected without
/// attempting the allocation.
#[test]
fn sec_002_huge_declared_string_is_rejected() {
    match parse_osr(&read("huge_string.osr"), Some(14)) {
        Err(EngineError::StringTooLong { .. }) => {}
        Err(EngineError::UnexpectedEof { .. }) => {}
        other => panic!("expected StringTooLong or UnexpectedEof, got {other:?}"),
    }
}

/// SEC-004: NaN and Infinity in numeric fields must not propagate into the model.
///
/// A NaN that reaches the engine is worse than a parse failure: it silently
/// poisons every downstream comparison (NaN compares false against everything),
/// so a NaN hit-object time would make the object simply never judge.
#[test]
fn sec_004_nan_and_infinity_are_handled() {
    let text = String::from_utf8(read("nan_timing.osu")).expect("fixture is UTF-8");

    match parse_osu(&text) {
        Err(_) => {} // rejecting outright is fine
        Ok(b) => {
            // If accepted, nothing non-finite may survive into the model.
            for (i, o) in b.hit_objects.iter().enumerate() {
                assert!(
                    o.time.is_finite(),
                    "hit object {i} has non-finite time {}",
                    o.time
                );
                assert!(o.x.is_finite() && o.y.is_finite(), "object {i} has NaN pos");
            }
            for (i, t) in b.timing_points.iter().enumerate() {
                assert!(t.time.is_finite(), "timing point {i} has non-finite time");
                assert!(t.beat_length.is_finite(), "timing point {i} has NaN length");
            }
            for (name, v) in [
                ("hp", b.hp),
                ("cs", b.cs),
                ("od", b.od),
                ("ar", b.ar),
                ("slider_multiplier", b.slider_multiplier),
            ] {
                assert!(v.is_finite(), "difficulty {name} is non-finite: {v}");
            }
        }
    }
}

/// SEC-005: a large object count must parse within bounds, not blow up.
///
/// Built in-process rather than committed: a 100k-object fixture would be a
/// multi-MB file in the repo for no benefit.
#[test]
fn sec_005_many_hit_objects_parse_within_bounds() {
    let mut m = String::from(
        "osu file format v14\n\n\
         [General]\nMode: 0\n\n\
         [Difficulty]\nHPDrainRate:5\nCircleSize:4\nOverallDifficulty:8\n\
         ApproachRate:9\nSliderMultiplier:1.4\nSliderTickRate:1\n\n\
         [TimingPoints]\n0,500,4,2,0,100,1,0\n\n\
         [HitObjects]\n",
    );

    for i in 0..100_000 {
        m.push_str(&format!("256,192,{},1,0,0:0:0:0:\n", i * 10));
    }

    let b = parse_osu(&m).expect("100k objects should parse");
    assert_eq!(b.hit_objects.len(), 100_000);
}

/// SEC-006: invalid UTF-8 in a string field is an error, never a panic.
#[test]
fn sec_006_invalid_utf8_is_rejected() {
    // mode 0, version, then a string declaring 3 bytes of invalid UTF-8.
    let mut data = vec![0u8];
    data.extend_from_slice(&20_140_721i32.to_le_bytes());
    data.extend_from_slice(&[0x0B, 0x03, 0xFF, 0xFE, 0xFD]);

    match parse_osr(&data, Some(14)) {
        Err(EngineError::InvalidUtf8 { .. }) => {}
        other => panic!("expected InvalidUtf8, got {other:?}"),
    }
}

/// SEC-007: a zero-byte file is an error, never a panic.
#[test]
fn sec_007_empty_file_is_rejected() {
    match parse_osr(&read("empty.osr"), Some(14)) {
        Err(EngineError::UnexpectedEof { .. }) => {}
        other => panic!("expected UnexpectedEof for empty .osr, got {other:?}"),
    }

    // The .osu parser must be equally unimpressed by nothing at all.
    assert!(parse_osu("").is_err(), "empty .osu should not parse");
}

/// A truncated but otherwise well-formed replay must not panic.
#[test]
fn truncated_replay_is_rejected() {
    match parse_osr(&read("truncated.osr"), Some(14)) {
        Err(EngineError::UnexpectedEof { .. }) => {}
        other => panic!("expected UnexpectedEof, got {other:?}"),
    }
}

/// A replay for a ruleset we do not implement must be rejected, not
/// misinterpreted as osu! Standard.
#[test]
fn unknown_game_mode_is_rejected() {
    match parse_osr(&read("invalid_magic.osr"), Some(14)) {
        Err(EngineError::InvalidGameMode { mode: 99, .. }) => {}
        other => panic!("expected InvalidGameMode, got {other:?}"),
    }
}

/// Coordinates far outside the playfield must not panic the `.osu` parser.
///
/// lazer bounds coordinates at MAX_COORDINATE_VALUE and throws past it; either
/// rejecting or parsing to a finite value is acceptable, panicking is not.
#[test]
fn extreme_coordinates_do_not_panic() {
    let text = String::from_utf8(read("negative_coords.osu")).expect("fixture is UTF-8");

    if let Ok(b) = parse_osu(&text) {
        for o in &b.hit_objects {
            assert!(o.x.is_finite() && o.y.is_finite());
        }
    }
}

/// A beatmap missing every section the engine needs must be a typed error.
#[test]
fn missing_sections_is_rejected() {
    let text = String::from_utf8(read("missing_sections.osu")).expect("fixture is UTF-8");
    assert!(
        parse_osu(&text).is_err(),
        "a beatmap with no [Difficulty]/[HitObjects] should not parse"
    );
}
